
index:
    path: /
    controller: App\Controller\DefaultController::index

todoList:
    path: /todoList
    controller: App\Controller\TodoController::list

viewTodoItem:
    path: /todoList/item/{itemId}
    controller: App\Controller\TodoController::viewItem

deleteTodoItem:
    path: /todoList/deleteItem/{itemId}
    controller: App\Controller\TodoController::deleteItem
    methods: [DELETE]

toggleTodoItemDone:
    path: /todoList/item/{itemId}/toggleIsDone
    controller: App\Controller\TodoController::toggleItemIsDone
    methods: [POST]
